"""init

Revision ID: e5f4b74d736f
Revises: 914784415fda
Create Date: 2020-03-22 16:39:00.466144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f4b74d736f'
down_revision = '914784415fda'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi',
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('kpi', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('kpi_id', name=op.f('pk_kpi'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi')
    # ### end Alembic commands ###
