"""init

Revision ID: 5cefd88c4917
Revises: e5f4b74d736f
Create Date: 2020-03-22 16:56:08.502337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cefd88c4917'
down_revision = 'e5f4b74d736f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('report_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'report_id')
    # ### end Alembic commands ###
