"""init

Revision ID: 696669e25c6a
Revises: a1c6c0f4b23d
Create Date: 2020-03-20 19:43:41.544330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696669e25c6a'
down_revision = 'a1c6c0f4b23d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('published', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'published')
    # ### end Alembic commands ###
