"""init

Revision ID: 4d0cfc7b2a14
Revises: 5cefd88c4917
Create Date: 2020-03-22 17:41:17.764402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0cfc7b2a14'
down_revision = '5cefd88c4917'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('kpi_name', sa.Text(), nullable=False))
    op.add_column('kpi', sa.Column('value', sa.Integer(), nullable=False))
    op.drop_column('kpi', 'kpi')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('kpi', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('kpi', 'value')
    op.drop_column('kpi', 'kpi_name')
    # ### end Alembic commands ###
