"""init

Revision ID: a0aef5249fa1
Revises: 300b12acbbac
Create Date: 2020-04-21 01:06:29.264814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0aef5249fa1'
down_revision = '300b12acbbac'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
