"""init

Revision ID: 1467a5ca3b10
Revises: 
Create Date: 2020-12-24 18:34:57.585163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1467a5ca3b10'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi',
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('kpi_name', sa.Text(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('kpi_id', name=op.f('pk_kpi'))
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('highlight', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('customer_gained', sa.Text(), nullable=True),
    sa.Column('order', sa.Text(), nullable=True),
    sa.Column('revenue_1', sa.Text(), nullable=True),
    sa.Column('revenue_2', sa.Text(), nullable=True),
    sa.Column('revenue_3', sa.Text(), nullable=True),
    sa.Column('revenue_4', sa.Text(), nullable=True),
    sa.Column('revenue_YTD', sa.Text(), nullable=True),
    sa.Column('revenue_FY', sa.Text(), nullable=True),
    sa.Column('revenue_plan', sa.Text(), nullable=True),
    sa.Column('profit_1', sa.Text(), nullable=True),
    sa.Column('profit_2', sa.Text(), nullable=True),
    sa.Column('profit_3', sa.Text(), nullable=True),
    sa.Column('profit_4', sa.Text(), nullable=True),
    sa.Column('profit_YTD', sa.Text(), nullable=True),
    sa.Column('profit_FY', sa.Text(), nullable=True),
    sa.Column('profit_plan', sa.Text(), nullable=True),
    sa.Column('EBITDA_1', sa.Text(), nullable=True),
    sa.Column('EBITDA_2', sa.Text(), nullable=True),
    sa.Column('EBITDA_3', sa.Text(), nullable=True),
    sa.Column('EBITDA_4', sa.Text(), nullable=True),
    sa.Column('EBITDA_YTD', sa.Text(), nullable=True),
    sa.Column('EBITDA_FY', sa.Text(), nullable=True),
    sa.Column('EBITDA_plan', sa.Text(), nullable=True),
    sa.Column('cf_1', sa.Text(), nullable=True),
    sa.Column('cf_2', sa.Text(), nullable=True),
    sa.Column('cf_3', sa.Text(), nullable=True),
    sa.Column('cf_4', sa.Text(), nullable=True),
    sa.Column('cf_YTD', sa.Text(), nullable=True),
    sa.Column('cf_FY', sa.Text(), nullable=True),
    sa.Column('cf_plan', sa.Text(), nullable=True),
    sa.Column('explain', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('unique_filename', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('my_index', 'reports', [sa.text('year DESC'), sa.text('quarter DESC')], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('my_index', table_name='reports')
    op.drop_table('reports')
    op.drop_table('kpi')
    # ### end Alembic commands ###
