"""init

Revision ID: 7d037cdbce49
Revises: d30058c46b15
Create Date: 2020-03-30 12:28:20.921945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d037cdbce49'
down_revision = 'd30058c46b15'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi',
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('kpi_name', sa.Text(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('kpi_id', name=op.f('pk_kpi'))
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('highlight1', sa.Text(), nullable=True),
    sa.Column('highlight2', sa.Text(), nullable=True),
    sa.Column('highlight3', sa.Text(), nullable=True),
    sa.Column('highlight4', sa.Text(), nullable=True),
    sa.Column('highlight5', sa.Text(), nullable=True),
    sa.Column('highlight6', sa.Text(), nullable=True),
    sa.Column('highlight7', sa.Text(), nullable=True),
    sa.Column('highlight8', sa.Text(), nullable=True),
    sa.Column('highlight9', sa.Text(), nullable=True),
    sa.Column('operation1', sa.Text(), nullable=True),
    sa.Column('operation2', sa.Text(), nullable=True),
    sa.Column('operation3', sa.Text(), nullable=True),
    sa.Column('operation4', sa.Text(), nullable=True),
    sa.Column('operation5', sa.Text(), nullable=True),
    sa.Column('operation6', sa.Text(), nullable=True),
    sa.Column('operation7', sa.Text(), nullable=True),
    sa.Column('operation8', sa.Text(), nullable=True),
    sa.Column('operation9', sa.Text(), nullable=True),
    sa.Column('strategy1', sa.Text(), nullable=True),
    sa.Column('strategy2', sa.Text(), nullable=True),
    sa.Column('strategy3', sa.Text(), nullable=True),
    sa.Column('strategy4', sa.Text(), nullable=True),
    sa.Column('strategy5', sa.Text(), nullable=True),
    sa.Column('strategy6', sa.Text(), nullable=True),
    sa.Column('strategy7', sa.Text(), nullable=True),
    sa.Column('strategy8', sa.Text(), nullable=True),
    sa.Column('strategy9', sa.Text(), nullable=True),
    sa.Column('customer_gained1', sa.Text(), nullable=True),
    sa.Column('customer_gained2', sa.Text(), nullable=True),
    sa.Column('customer_gained3', sa.Text(), nullable=True),
    sa.Column('customer_gained4', sa.Text(), nullable=True),
    sa.Column('customer_gained5', sa.Text(), nullable=True),
    sa.Column('customer_gained6', sa.Text(), nullable=True),
    sa.Column('customer_gained7', sa.Text(), nullable=True),
    sa.Column('customer_gained8', sa.Text(), nullable=True),
    sa.Column('customer_gained9', sa.Text(), nullable=True),
    sa.Column('order1', sa.Text(), nullable=True),
    sa.Column('order2', sa.Text(), nullable=True),
    sa.Column('order3', sa.Text(), nullable=True),
    sa.Column('order4', sa.Text(), nullable=True),
    sa.Column('order5', sa.Text(), nullable=True),
    sa.Column('order6', sa.Text(), nullable=True),
    sa.Column('order7', sa.Text(), nullable=True),
    sa.Column('order8', sa.Text(), nullable=True),
    sa.Column('order9', sa.Text(), nullable=True),
    sa.Column('revenue_1', sa.Integer(), nullable=True),
    sa.Column('revenue_2', sa.Integer(), nullable=True),
    sa.Column('revenue_3', sa.Integer(), nullable=True),
    sa.Column('revenue_4', sa.Integer(), nullable=True),
    sa.Column('revenue_YTD', sa.Integer(), nullable=True),
    sa.Column('revenue_FY', sa.Integer(), nullable=True),
    sa.Column('revenue_plan', sa.Integer(), nullable=True),
    sa.Column('profit_1', sa.Integer(), nullable=True),
    sa.Column('profit_2', sa.Integer(), nullable=True),
    sa.Column('profit_3', sa.Integer(), nullable=True),
    sa.Column('profit_4', sa.Integer(), nullable=True),
    sa.Column('profit_YTD', sa.Integer(), nullable=True),
    sa.Column('profit_FY', sa.Integer(), nullable=True),
    sa.Column('profit_plan', sa.Integer(), nullable=True),
    sa.Column('EBITDA_1', sa.Integer(), nullable=True),
    sa.Column('EBITDA_2', sa.Integer(), nullable=True),
    sa.Column('EBITDA_3', sa.Integer(), nullable=True),
    sa.Column('EBITDA_4', sa.Integer(), nullable=True),
    sa.Column('EBITDA_YTD', sa.Integer(), nullable=True),
    sa.Column('EBITDA_FY', sa.Integer(), nullable=True),
    sa.Column('EBITDA_plan', sa.Integer(), nullable=True),
    sa.Column('cf_1', sa.Integer(), nullable=True),
    sa.Column('cf_2', sa.Integer(), nullable=True),
    sa.Column('cf_3', sa.Integer(), nullable=True),
    sa.Column('cf_4', sa.Integer(), nullable=True),
    sa.Column('cf_YTD', sa.Integer(), nullable=True),
    sa.Column('cf_FY', sa.Integer(), nullable=True),
    sa.Column('cf_plan', sa.Integer(), nullable=True),
    sa.Column('explain', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('unique_filename', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('my_index', 'reports', [sa.text('year DESC'), sa.text('quarter DESC')], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('my_index', table_name='reports')
    op.drop_table('reports')
    op.drop_table('kpi')
    # ### end Alembic commands ###
