"""init

Revision ID: faef89c46ff0
Revises: a8db6ff7dd44
Create Date: 2020-03-19 16:08:55.420264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faef89c46ff0'
down_revision = 'a8db6ff7dd44'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('EBITDA_1', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('EBITDA_2', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('EBITDA_3', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('EBITDA_4', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('EBITDA_FY', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('EBITDA_YTD', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('EBITDA_plan', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('cf_1', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('cf_2', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('cf_3', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('cf_4', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('cf_FY', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('cf_YTD', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('cf_plan', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('profit_1', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('profit_2', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('profit_3', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('profit_4', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('profit_FY', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('profit_YTD', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('profit_plan', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('revenue_1', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('revenue_2', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('revenue_3', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('revenue_4', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('revenue_FY', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('revenue_YTD', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('revenue_plan', sa.Integer(), nullable=True))
    op.drop_column('reports', 'EBITDA')
    op.drop_column('reports', 'cash_flow')
    op.drop_column('reports', 'profit')
    op.drop_column('reports', 'revenue')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('revenue', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('profit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('cash_flow', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('EBITDA', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'revenue_plan')
    op.drop_column('reports', 'revenue_YTD')
    op.drop_column('reports', 'revenue_FY')
    op.drop_column('reports', 'revenue_4')
    op.drop_column('reports', 'revenue_3')
    op.drop_column('reports', 'revenue_2')
    op.drop_column('reports', 'revenue_1')
    op.drop_column('reports', 'profit_plan')
    op.drop_column('reports', 'profit_YTD')
    op.drop_column('reports', 'profit_FY')
    op.drop_column('reports', 'profit_4')
    op.drop_column('reports', 'profit_3')
    op.drop_column('reports', 'profit_2')
    op.drop_column('reports', 'profit_1')
    op.drop_column('reports', 'cf_plan')
    op.drop_column('reports', 'cf_YTD')
    op.drop_column('reports', 'cf_FY')
    op.drop_column('reports', 'cf_4')
    op.drop_column('reports', 'cf_3')
    op.drop_column('reports', 'cf_2')
    op.drop_column('reports', 'cf_1')
    op.drop_column('reports', 'EBITDA_plan')
    op.drop_column('reports', 'EBITDA_YTD')
    op.drop_column('reports', 'EBITDA_FY')
    op.drop_column('reports', 'EBITDA_4')
    op.drop_column('reports', 'EBITDA_3')
    op.drop_column('reports', 'EBITDA_2')
    op.drop_column('reports', 'EBITDA_1')
    # ### end Alembic commands ###
