"""init

Revision ID: 914784415fda
Revises: 696669e25c6a
Create Date: 2020-03-22 16:30:16.855344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914784415fda'
down_revision = '696669e25c6a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
