"""init

Revision ID: 457938db7219
Revises: 
Create Date: 2020-03-07 20:00:07.419423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457938db7219'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('customer_gained', sa.Text(), nullable=True),
    sa.Column('orders', sa.Text(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Integer(), nullable=True),
    sa.Column('EBITDA', sa.Integer(), nullable=True),
    sa.Column('cash_flow', sa.Integer(), nullable=True),
    sa.Column('explain', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('my_index', 'reports', [sa.text('year DESC'), sa.text('quarter DESC')], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('my_index', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
