"""init

Revision ID: 6c13e417d377
Revises: b9c402a2e75d
Create Date: 2020-04-12 03:21:16.484137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c13e417d377'
down_revision = 'b9c402a2e75d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
