"""tester

Revision ID: a1c6c0f4b23d
Revises: 9a576b86fe8f
Create Date: 2020-03-20 11:48:00.818663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c6c0f4b23d'
down_revision = '9a576b86fe8f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('customer_gained1', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('customer_gained2', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('customer_gained3', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('customer_gained4', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('customer_gained5', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('customer_gained6', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('customer_gained7', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('customer_gained8', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('customer_gained9', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('highlight1', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('highlight2', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('highlight3', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('highlight4', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('highlight5', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('highlight6', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('highlight7', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('highlight8', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('highlight9', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('operation1', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('operation2', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('operation3', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('operation4', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('operation5', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('operation6', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('operation7', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('operation8', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('operation9', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('order1', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('order2', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('order3', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('order4', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('order5', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('order6', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('order7', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('order8', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('order9', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('strategy1', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('strategy2', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('strategy3', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('strategy4', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('strategy5', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('strategy6', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('strategy7', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('strategy8', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('strategy9', sa.Text(), nullable=True))
    op.drop_column('reports', 'operation')
    op.drop_column('reports', 'customer_gained')
    op.drop_column('reports', 'highlights')
    op.drop_column('reports', 'orders')
    op.drop_column('reports', 'strategy')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('strategy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('orders', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('highlights', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('customer_gained', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('operation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'strategy9')
    op.drop_column('reports', 'strategy8')
    op.drop_column('reports', 'strategy7')
    op.drop_column('reports', 'strategy6')
    op.drop_column('reports', 'strategy5')
    op.drop_column('reports', 'strategy4')
    op.drop_column('reports', 'strategy3')
    op.drop_column('reports', 'strategy2')
    op.drop_column('reports', 'strategy1')
    op.drop_column('reports', 'order9')
    op.drop_column('reports', 'order8')
    op.drop_column('reports', 'order7')
    op.drop_column('reports', 'order6')
    op.drop_column('reports', 'order5')
    op.drop_column('reports', 'order4')
    op.drop_column('reports', 'order3')
    op.drop_column('reports', 'order2')
    op.drop_column('reports', 'order1')
    op.drop_column('reports', 'operation9')
    op.drop_column('reports', 'operation8')
    op.drop_column('reports', 'operation7')
    op.drop_column('reports', 'operation6')
    op.drop_column('reports', 'operation5')
    op.drop_column('reports', 'operation4')
    op.drop_column('reports', 'operation3')
    op.drop_column('reports', 'operation2')
    op.drop_column('reports', 'operation1')
    op.drop_column('reports', 'highlight9')
    op.drop_column('reports', 'highlight8')
    op.drop_column('reports', 'highlight7')
    op.drop_column('reports', 'highlight6')
    op.drop_column('reports', 'highlight5')
    op.drop_column('reports', 'highlight4')
    op.drop_column('reports', 'highlight3')
    op.drop_column('reports', 'highlight2')
    op.drop_column('reports', 'highlight1')
    op.drop_column('reports', 'customer_gained9')
    op.drop_column('reports', 'customer_gained8')
    op.drop_column('reports', 'customer_gained7')
    op.drop_column('reports', 'customer_gained6')
    op.drop_column('reports', 'customer_gained5')
    op.drop_column('reports', 'customer_gained4')
    op.drop_column('reports', 'customer_gained3')
    op.drop_column('reports', 'customer_gained2')
    op.drop_column('reports', 'customer_gained1')
    # ### end Alembic commands ###
