"""init

Revision ID: 00cf4197c49f
Revises: 2e5266541f34
Create Date: 2020-03-19 15:14:34.430972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cf4197c49f'
down_revision = '2e5266541f34'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('customer_gained', sa.Text(), nullable=True),
    sa.Column('orders', sa.Text(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Integer(), nullable=True),
    sa.Column('EBITDA', sa.Integer(), nullable=True),
    sa.Column('cash_flow', sa.Integer(), nullable=True),
    sa.Column('explain', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('unique_filename', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('my_index', 'reports', [sa.text('year DESC'), sa.text('quarter DESC')], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
