"""init

Revision ID: a8db6ff7dd44
Revises: 00cf4197c49f
Create Date: 2020-03-19 15:24:59.276179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8db6ff7dd44'
down_revision = '00cf4197c49f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('customer_gained', sa.Text(), nullable=True),
    sa.Column('orders', sa.Text(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Integer(), nullable=True),
    sa.Column('EBITDA', sa.Integer(), nullable=True),
    sa.Column('cash_flow', sa.Integer(), nullable=True),
    sa.Column('explain', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('unique_filename', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('my_index', 'reports', [sa.text('year DESC'), sa.text('quarter DESC')], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('my_index', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
