"""init

Revision ID: f31313758073
Revises: 4d0cfc7b2a14
Create Date: 2020-03-25 19:12:43.063788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31313758073'
down_revision = '4d0cfc7b2a14'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('target', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.Text(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    op.drop_column('kpi', 'target')
    # ### end Alembic commands ###
